# Generated by Django 3.0.3 on 2020-04-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='amount_invested',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='My portfolio', max_length=50),
        ),
    ]
